# SERVER CONFIG
server:
  port: 8881

# APPLICATION CONFIG
spring:
  application:
           name: PRODUCT-DISCOUNT-MANAGEMENT
# DATABASE CONFIGURATION
  datasource:
            url: jdbc:mysql://localhost:3306/pdm?createDatabaseIfNotExist=true
            username: root
            password: 2553
            driver-class-name: com.mysql.cj.jdbc.Driver
# JPA CONFIGURATION
  jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
             dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
